# Generated by Django 5.1.3 on 2025-01-01 16:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150)),
                ("user_email", models.CharField(max_length=254, null=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        choices=[
                            ("USER", "User Management"),
                            ("ROLE", "Role Management"),
                            ("MENU", "Menu Management"),
                        ],
                        max_length=20,
                    ),
                ),
                ("resource_id", models.CharField(max_length=50)),
                ("resource_type", models.CharField(max_length=50)),
                ("detail", models.JSONField()),
                ("ip_address", models.GenericIPAddressField(null=True)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("status", models.BooleanField(default=True)),
                ("message", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "action", "module", "timestamp"],
                        name="core_auditl_user_id_6852d2_idx",
                    ),
                    models.Index(
                        fields=["resource_type", "resource_id"],
                        name="core_auditl_resourc_a674ad_idx",
                    ),
                ],
            },
        ),
    ]
