# Generated by Django 5.1.3 on 2024-12-11 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SysRole",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        max_length=30, null=True, verbose_name="Role Name"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Role Permission Code"
                    ),
                ),
                (
                    "create_time",
                    models.DateField(null=True, verbose_name="Created Time"),
                ),
                (
                    "update_time",
                    models.DateField(null=True, verbose_name="Updated Time"),
                ),
                (
                    "remark",
                    models.CharField(
                        max_length=500, null=True, verbose_name="Comment Time"
                    ),
                ),
            ],
            options={
                "db_table": "sys_role",
            },
        ),
        migrations.CreateModel(
            name="SysUserRole",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="role.sysrole"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "sys_user_role",
            },
        ),
    ]
