# Generated by Django 5.1.3 on 2024-12-28 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("role", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sysrole",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deletion Date"
            ),
        ),
        migrations.AddField(
            model_name="sysrole",
            name="is_system",
            field=models.BooleanField(default=False, verbose_name="Is System Role"),
        ),
        migrations.AddField(
            model_name="sysrole",
            name="status",
            field=models.IntegerField(default=1, verbose_name="Status"),
        ),
    ]
