# Generated by Django 5.1.3 on 2024-12-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("role", "0002_sysrole_deleted_at_sysrole_is_system_sysrole_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sysrole",
            name="create_time",
            field=models.DateTimeField(null=True, verbose_name="Created Time"),
        ),
        migrations.AlterField(
            model_name="sysrole",
            name="update_time",
            field=models.DateTimeField(null=True, verbose_name="Updated Time"),
        ),
    ]
