# Generated by Django 5.1.3 on 2024-12-28 13:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("role", "0003_alter_sysrole_create_time_alter_sysrole_update_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sysrole",
            name="create_time",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Created Time",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="sysrole",
            name="remark",
            field=models.CharField(max_length=500, null=True, verbose_name="Comment"),
        ),
        migrations.AlterField(
            model_name="sysrole",
            name="update_time",
            field=models.DateTimeField(
                auto_now=True,
                default=django.utils.timezone.now,
                verbose_name="Updated Time",
            ),
            preserve_default=False,
        ),
    ]
