# Generated by Django 5.1.3 on 2024-12-29 09:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("role", "0004_alter_sysrole_create_time_alter_sysrole_remark_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sysrole",
            name="code",
            field=models.CharField(
                max_length=100,
                verbose_name="Role Permission Code",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="sysrole",
            name="name",
            field=models.CharField(
                max_length=30,
                verbose_name="Role Name",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="sysrole",
            name="remark",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Comment"
            ),
        ),
    ]
