# Generated by Django 5.1.3 on 2024-11-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SysUser",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "username",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="User Name"
                    ),
                ),
                ("password", models.CharField(max_length=100, verbose_name="Password")),
                (
                    "avatar",
                    models.CharField(max_length=255, null=True, verbose_name="Avatar"),
                ),
                (
                    "email",
                    models.CharField(max_length=100, null=True, verbose_name="Email"),
                ),
                (
                    "phone",
                    models.CharField(max_length=11, null=True, verbose_name="Phone"),
                ),
                (
                    "login_date",
                    models.DateTimeField(null=True, verbose_name="Login Date"),
                ),
                ("status", models.IntegerField(null=True, verbose_name="Status")),
                (
                    "create_time",
                    models.DateTimeField(null=True, verbose_name="Create Time"),
                ),
                (
                    "update_time",
                    models.DateTimeField(null=True, verbose_name="Update Time"),
                ),
                (
                    "comment",
                    models.CharField(max_length=500, null=True, verbose_name="Comment"),
                ),
            ],
            options={
                "db_table": "sys_user",
            },
        ),
    ]
