# Generated by Django 5.1.3 on 2024-12-17 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_sysuser_managers_sysuser_date_joined_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sysuser",
            name="login_date",
        ),
    ]
