# Generated by Django 5.1.3 on 2024-12-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_remove_sysuser_login_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sysuser",
            name="is_active",
        ),
        migrations.AddField(
            model_name="sysuser",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deletion Date"
            ),
        ),
    ]
