# Generated by Django 5.1.3 on 2024-12-11 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sysmenu",
            name="menu_type",
            field=models.CharField(
                max_length=1, null=True, verbose_name="Menu Type（Catalog Menu Button）"
            ),
        ),
    ]
