# Generated by Django 5.1.3 on 2024-12-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0002_alter_sysmenu_menu_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="sysmenu",
            name="keep_alive",
            field=models.BooleanField(default=False, verbose_name="Keep Tab State"),
        ),
        migrations.AddField(
            model_name="sysmenu",
            name="title",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Display Title"
            ),
        ),
    ]
