# Generated by Django 5.1.3 on 2024-12-29 19:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0003_sysmenu_keep_alive_sysmenu_title"),
        ("role", "0005_alter_sysrole_code_alter_sysrole_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sysmenu",
            options={"ordering": ["order_num"]},
        ),
        migrations.RemoveField(
            model_name="sysmenu",
            name="keep_alive",
        ),
        migrations.RemoveField(
            model_name="sysmenu",
            name="menu_type",
        ),
        migrations.RemoveField(
            model_name="sysmenu",
            name="title",
        ),
        migrations.AddField(
            model_name="sysmenu",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deletion Time"
            ),
        ),
        migrations.AddField(
            model_name="sysmenu",
            name="status",
            field=models.IntegerField(
                default=1, verbose_name="Status(0:disabled,1:enabled)"
            ),
        ),
        migrations.AlterField(
            model_name="sysmenu",
            name="component",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Component Path"
            ),
        ),
        migrations.AlterField(
            model_name="sysmenu",
            name="create_time",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Created Time",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="sysmenu",
            name="icon",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Menu Icon"
            ),
        ),
        migrations.AlterField(
            model_name="sysmenu",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Menu Name"),
        ),
        migrations.AlterField(
            model_name="sysmenu",
            name="order_num",
            field=models.IntegerField(default=0, verbose_name="Order"),
        ),
        migrations.AlterField(
            model_name="sysmenu",
            name="parent_id",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Parent Menu ID"
            ),
        ),
        migrations.AlterField(
            model_name="sysmenu",
            name="path",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Router Path"
            ),
        ),
        migrations.AlterField(
            model_name="sysmenu",
            name="perms",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Permission String"
            ),
        ),
        migrations.AlterField(
            model_name="sysmenu",
            name="remark",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Comment"
            ),
        ),
        migrations.AlterField(
            model_name="sysmenu",
            name="update_time",
            field=models.DateTimeField(
                auto_now=True,
                default=django.utils.timezone.now,
                verbose_name="Updated Time",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="sysrolemenu",
            name="menu",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="menu.sysmenu"
            ),
        ),
        migrations.AlterField(
            model_name="sysrolemenu",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="role.sysrole"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="sysrolemenu",
            unique_together={("role", "menu")},
        ),
    ]
