# Generated by Django 5.1.3 on 2025-01-01 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0004_alter_sysmenu_options_remove_sysmenu_keep_alive_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sysmenu",
            options={"ordering": ["parent_id", "order_num"]},
        ),
    ]
